# Text Summarization


#### https://medium.com/luisfredgs/automatic-text-summarization-with-machine-learning-an-overview-68ded5717a25
#### https://medium.com/sciforce/towards-automatic-text-summarization-extractive-methods-e8439cd54715#:~:text=Extractive%20summarization%20means%20identifying%20important,text%20using%20advanced%20natural%20language
#### https://medium.com/luisfredgs/automatic-text-summarization-made-simple-with-python-f9c3c645e34a
#### https://medium.com/sciforce/towards-automatic-text-summarization-extractive-methods-e8439cd54715

## Extractive Text Summarization

### Term Frequency Method

In [371]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation

In [372]:
document=open('half girl friend.txt','r')

In [373]:
data=document.read()
data

"Madhav Jha, a rural boy from Dumraon, a village in Bihar, comes to meet the author, who is actually Chetan Bhagat, and leaves behind a few journals from his \nhalf-girlfriend, who he believes has died. Chetan Bhagat calls him up the next morning to hear his story. He starts by describing his trouble entering St. Stephens,\nas his English wasn't good enough. Being a good basketball player, Madhav gets finally through sports quota.\n\nThe rich and beautiful Riya Somani is a girl from Delhi, who is also selected through the sports quota. Madhav and Riya become close 'friends' due to their \nassociation with basketball. Madhav wants to make her his girlfriend, but she refuses. He demands that they get physical. Offended by his obscene ultimatum, \nRiya parts company with him and tells him not to talk to her anymore.\n\nA year later, Riya marries her childhood friend Rohan and settles in London, where Rohan has a big business. Finding Delhi unbearable on grounds of losing Riya, \nMadhav de

In [374]:
stopwords=list(STOP_WORDS)
stopwords

['part',
 'unless',
 'always',
 'me',
 'then',
 'call',
 'every',
 'however',
 'beforehand',
 'throughout',
 'side',
 'mine',
 'n‘t',
 'everyone',
 'last',
 'are',
 'already',
 'much',
 'was',
 'whereafter',
 'please',
 'seems',
 'ours',
 'just',
 'anywhere',
 'say',
 'behind',
 'two',
 'another',
 'get',
 'back',
 'six',
 'although',
 'were',
 'onto',
 'below',
 'who',
 'not',
 'myself',
 'afterwards',
 'wherever',
 'elsewhere',
 'did',
 'therefore',
 'done',
 'our',
 'us',
 'whereas',
 'twenty',
 '‘ll',
 'do',
 'neither',
 'amongst',
 'though',
 'and',
 'became',
 'cannot',
 'herself',
 'latter',
 'same',
 'whereupon',
 'whether',
 'himself',
 'forty',
 'the',
 'since',
 'various',
 'even',
 'formerly',
 'third',
 'upon',
 '‘m',
 'its',
 'or',
 'where',
 'in',
 '’ve',
 'nowhere',
 'through',
 'ca',
 'into',
 'being',
 'hundred',
 'least',
 'you',
 'per',
 'ten',
 'nine',
 'from',
 'using',
 'whole',
 'a',
 'mostly',
 'fifteen',
 'any',
 'without',
 'really',
 're',
 'am',
 'only',
 '

In [375]:
nlp=spacy.load('en_core_web_sm')

In [376]:
docx=nlp(data)

In [377]:
punctuation=punctuation + '\n'
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~\n'

In [280]:
word_freq={}
for word in docx:
    if word.text.lower() not in stopwords:
        if word.text.lower() not in punctuation:
            if word.text not in word_freq.keys():
                word_freq[word.text]=1
            else:
                word_freq[word.text]+=1

In [281]:
word_freq

{'Madhav': 12,
 'Jha': 1,
 'rural': 2,
 'boy': 1,
 'Dumraon': 3,
 'village': 1,
 'Bihar': 2,
 'comes': 3,
 'meet': 2,
 'author': 2,
 'actually': 1,
 'Chetan': 2,
 'Bhagat': 2,
 'leaves': 2,
 'journals': 2,
 'half': 2,
 'girlfriend': 2,
 'believes': 1,
 'died': 1,
 'calls': 1,
 'morning': 1,
 'hear': 1,
 'story': 1,
 'starts': 1,
 'describing': 1,
 'trouble': 1,
 'entering': 1,
 'St.': 1,
 'Stephens': 1,
 'English': 2,
 'good': 2,
 'basketball': 2,
 'player': 1,
 'gets': 1,
 'finally': 2,
 'sports': 2,
 'quota': 2,
 '\n\n': 5,
 'rich': 1,
 'beautiful': 1,
 'Riya': 11,
 'Somani': 1,
 'girl': 1,
 'Delhi': 2,
 'selected': 1,
 'close': 1,
 'friends': 1,
 'association': 1,
 'wants': 1,
 'refuses': 2,
 'demands': 1,
 'physical': 1,
 'Offended': 1,
 'obscene': 1,
 'ultimatum': 1,
 'parts': 1,
 'company': 1,
 'tells': 1,
 'talk': 1,
 'anymore': 1,
 'year': 1,
 'later': 2,
 'marries': 1,
 'childhood': 1,
 'friend': 1,
 'Rohan': 2,
 'settles': 1,
 'London': 1,
 'big': 1,
 'business': 1,
 'Finding

In [282]:
max_freq=max(word_freq.values())
max_freq

12

In [283]:
for word in word_freq.keys():
    word_freq[word]=(word_freq[word]/max_freq)

In [284]:
word_freq

{'Madhav': 1.0,
 'Jha': 0.08333333333333333,
 'rural': 0.16666666666666666,
 'boy': 0.08333333333333333,
 'Dumraon': 0.25,
 'village': 0.08333333333333333,
 'Bihar': 0.16666666666666666,
 'comes': 0.25,
 'meet': 0.16666666666666666,
 'author': 0.16666666666666666,
 'actually': 0.08333333333333333,
 'Chetan': 0.16666666666666666,
 'Bhagat': 0.16666666666666666,
 'leaves': 0.16666666666666666,
 'journals': 0.16666666666666666,
 'half': 0.16666666666666666,
 'girlfriend': 0.16666666666666666,
 'believes': 0.08333333333333333,
 'died': 0.08333333333333333,
 'calls': 0.08333333333333333,
 'morning': 0.08333333333333333,
 'hear': 0.08333333333333333,
 'story': 0.08333333333333333,
 'starts': 0.08333333333333333,
 'describing': 0.08333333333333333,
 'trouble': 0.08333333333333333,
 'entering': 0.08333333333333333,
 'St.': 0.08333333333333333,
 'Stephens': 0.08333333333333333,
 'English': 0.16666666666666666,
 'good': 0.16666666666666666,
 'basketball': 0.16666666666666666,
 'player': 0.083333

In [285]:
sentence_list=[sentence for sentence in docx.sents]
    

In [286]:
sentence_rank={}
for sent in sentence_list:
    for word in sent:
        if word.text.lower()in word_freq.keys():
            if len(sent.text.split(' '))<30:
                if sent not in sentence_rank.keys():
                    sentence_rank[sent]=word_freq[word.text.lower()]
                else:
                    sentence_rank[sent]+= word_freq[word.text.lower()]

In [287]:
sentence_rank

{Chetan Bhagat calls him up the next morning to hear his story.: 0.3333333333333333,
 He starts by describing his trouble entering St. Stephens,
 as his English wasn't good enough.: 0.5,
 Being a good basketball player, Madhav gets finally through sports quota.
 : 1.4166666666666665,
 The rich and beautiful Riya Somani is a girl from Delhi, who is also selected through the sports quota.: 0.6666666666666666,
 Madhav and Riya become close 'friends' due to their 
 association with basketball.: 0.41666666666666663,
 Madhav wants to make her his girlfriend, but she refuses.: 0.41666666666666663,
 He demands that they get physical.: 0.16666666666666666,
 Offended by his obscene ultimatum, 
 Riya parts company with him and tells him not to talk to her anymore.
 : 1.0,
 A year later, Riya marries her childhood friend Rohan and settles in London, where Rohan has a big business.: 0.75,
 Finding Delhi unbearable on grounds of losing Riya, 
 Madhav decides to settle in his hometown Dumraon and hel

In [288]:
print(max(sentence_rank.values()))

1.6666666666666665


In [289]:
from heapq import nlargest

In [290]:
summarize_sent=nlargest(7,sentence_rank,key=sentence_rank.get)

In [291]:
summarize_sent

[Madhav tries his best to convince Gates to fund his school, but to do so he has to prepare a speech, preferably in English.
 , After three 
 months of extensively searching, he finds her at Cafe Wha and the two reconcile and finally consummate their relationship.
 , Being a good basketball player, Madhav gets finally through sports quota.
 , Finding Delhi unbearable on grounds of losing Riya, 
 Madhav decides to settle in his hometown Dumraon and helps his mother, Rani Sahiba, who runs her school., “ Madhav decides to meet local MLA Ojha for financial help, but the MLA refuses to help., When Madhav attempts to track her down, he finds that she has cut all ties in India and has
  disappeared.
 , Offended by his obscene ultimatum, 
 Riya parts company with him and tells him not to talk to her anymore.
 ]

In [292]:
final_sent=[word.text for word in summarize_sent]

In [293]:
summary=' '.join(final_sent)

In [294]:
summary

'Madhav tries his best to convince Gates to fund his school, but to do so he has to prepare a speech, preferably in English.\n\n After three \nmonths of extensively searching, he finds her at Cafe Wha and the two reconcile and finally consummate their relationship.\n\n Being a good basketball player, Madhav gets finally through sports quota.\n\n Finding Delhi unbearable on grounds of losing Riya, \nMadhav decides to settle in his hometown Dumraon and helps his mother, Rani Sahiba, who runs her school. “ Madhav decides to meet local MLA Ojha for financial help, but the MLA refuses to help. When Madhav attempts to track her down, he finds that she has cut all ties in India and has\n disappeared.\n\n Offended by his obscene ultimatum, \nRiya parts company with him and tells him not to talk to her anymore.\n\n'

### Latent Semantic Analysis( LSA)

#### https://www.youtube.com/watch?v=OvzJiur55vo&ab_channel=MinsukHeo%ED%97%88%EB%AF%BC%EC%84%9D
#### https://www.youtube.com/watch?v=bzNch-dBCN8
#### https://www.datajango.com/topic-modeling-and-singular-value-decomposition-svd/

In [378]:
docx

Madhav Jha, a rural boy from Dumraon, a village in Bihar, comes to meet the author, who is actually Chetan Bhagat, and leaves behind a few journals from his 
half-girlfriend, who he believes has died. Chetan Bhagat calls him up the next morning to hear his story. He starts by describing his trouble entering St. Stephens,
as his English wasn't good enough. Being a good basketball player, Madhav gets finally through sports quota.

The rich and beautiful Riya Somani is a girl from Delhi, who is also selected through the sports quota. Madhav and Riya become close 'friends' due to their 
association with basketball. Madhav wants to make her his girlfriend, but she refuses. He demands that they get physical. Offended by his obscene ultimatum, 
Riya parts company with him and tells him not to talk to her anymore.

A year later, Riya marries her childhood friend Rohan and settles in London, where Rohan has a big business. Finding Delhi unbearable on grounds of losing Riya, 
Madhav decides to s

In [379]:
from nltk.stem import PorterStemmer
porter = PorterStemmer()
porter.stem(data)

"madhav jha, a rural boy from dumraon, a village in bihar, comes to meet the author, who is actually chetan bhagat, and leaves behind a few journals from his \nhalf-girlfriend, who he believes has died. chetan bhagat calls him up the next morning to hear his story. he starts by describing his trouble entering st. stephens,\nas his english wasn't good enough. being a good basketball player, madhav gets finally through sports quota.\n\nthe rich and beautiful riya somani is a girl from delhi, who is also selected through the sports quota. madhav and riya become close 'friends' due to their \nassociation with basketball. madhav wants to make her his girlfriend, but she refuses. he demands that they get physical. offended by his obscene ultimatum, \nriya parts company with him and tells him not to talk to her anymore.\n\na year later, riya marries her childhood friend rohan and settles in london, where rohan has a big business. finding delhi unbearable on grounds of losing riya, \nmadhav de

In [380]:
new_doc=[]
for sentence in docx.sents:
    a=[]
    for word in sentence:
        if word.text.lower() not in stopwords:
            if word.text.lower() not in punctuation:
                
                a.append(porter.stem(word.text.lower()))
                a.append(" ")
    l="".join(a)
    new_doc.append(l)
    #new_doc.append(" ")
print(new_doc)

['madhav jha rural boy dumraon villag bihar come meet author actual chetan bhagat leav journal half girlfriend believ die ', 'chetan bhagat call morn hear stori ', 'start describ troubl enter st. stephen english good ', 'good basketbal player madhav get final sport quota \n\n ', 'rich beauti riya somani girl delhi select sport quota ', 'madhav riya close friend associ basketbal ', 'madhav want girlfriend refus ', 'demand physic ', 'offend obscen ultimatum riya part compani tell talk anymor \n\n ', 'year later riya marri childhood friend rohan settl london rohan big busi ', 'find delhi unbear ground lose riya madhav decid settl hometown dumraon help mother rani sahiba run school ', 'see condit school ', '†“ proper class \n  toilet ', '†', '“ madhav decid meet local mla ojha financi help mla refus help ', 'opportun come ojha inform madhav bill gate visit school bihar ', 'madhav tri best convinc gate fund school prepar speech prefer english \n\n ', 'cours struggl come riya divorce ', 

In [381]:
from sklearn.feature_extraction.text import TfidfVectorizer
obj = TfidfVectorizer()
corpus=new_doc
X = obj.fit_transform(corpus)
print(X)

  (0, 36)	0.25473237004339955
  (0, 8)	0.25473237004339955
  (0, 54)	0.22606348735400528
  (0, 58)	0.22606348735400528
  (0, 65)	0.22606348735400528
  (0, 67)	0.22606348735400528
  (0, 10)	0.22606348735400528
  (0, 20)	0.22606348735400528
  (0, 0)	0.25473237004339955
  (0, 5)	0.22606348735400528
  (0, 78)	0.22606348735400528
  (0, 24)	0.2057225913754497
  (0, 12)	0.22606348735400528
  (0, 134)	0.25473237004339955
  (0, 39)	0.2057225913754497
  (0, 15)	0.25473237004339955
  (0, 104)	0.22606348735400528
  (0, 64)	0.25473237004339955
  (0, 76)	0.12238441715116379
  (1, 121)	0.42351776264533064
  (1, 59)	0.42351776264533064
  (1, 81)	0.42351776264533064
  (1, 18)	0.42351776264533064
  (1, 10)	0.37585290932462745
  (1, 20)	0.37585290932462745
  :	:
  (24, 96)	0.33558564013142683
  (24, 137)	0.33558564013142683
  (24, 17)	0.33558564013142683
  (24, 43)	0.33558564013142683
  (24, 107)	0.29781711723999366
  (24, 80)	0.2710199237908559
  (24, 47)	0.2710199237908559
  (24, 45)	0.2978171172399936

#### https://www.researchgate.net/post/What_are_the_significance_of_singular_value_decomposition
#### https://jonathan-hui.medium.com/machine-learning-singular-value-decomposition-svd-principal-component-analysis-pca-1d45e885e491#:~:text=In%20machine%20learning%20(ML)%2C,principal%20component%20analysis%20(PCA).&text=SVD%20allows%20us%20to%20extract%20and%20untangle%20information.

In [382]:
from scipy.sparse.linalg import svds
matrix = X.transpose()
u,s,v=svds(matrix)

In [383]:
u.shape,s.shape,v.shape

((140, 6), (6,), (6, 26))

In [384]:
u

array([[-4.35923480e-02, -9.32517985e-02, -4.65405332e-02,
         2.97685355e-02,  5.25382987e-02,  4.35164275e-02],
       [-8.00526404e-02, -8.37701960e-03, -1.16663846e-01,
        -7.00705220e-02, -4.05207165e-02,  4.99683387e-02],
       [-4.70189213e-02,  1.95468987e-02, -2.17953620e-02,
        -2.65565035e-02, -3.17667971e-02,  1.83182104e-02],
       [-9.09526879e-02,  6.26086499e-02, -4.54809097e-02,
         9.68572597e-02, -9.65035467e-02,  7.91754142e-02],
       [ 6.80225390e-02, -3.64821674e-02,  2.08704304e-02,
         6.91244866e-02, -1.22530498e-02,  2.78608108e-02],
       [-1.78239634e-02, -5.07195672e-02, -1.01799976e-01,
         2.12917715e-02,  1.17847341e-01,  9.92664104e-02],
       [-8.41440434e-02,  1.38019534e-01, -4.42205843e-02,
         2.41351904e-01, -1.64873664e-01,  1.08933710e-01],
       [-6.16217179e-02,  9.89106913e-02, -1.60276943e-02,
         7.42050671e-02, -7.06817862e-02,  3.37512931e-02],
       [-4.35923480e-02, -9.32517985e-02, -4.654

In [385]:
s

array([1.09497172, 1.11690113, 1.14010031, 1.15327013, 1.19546736,
       1.43983171])

In [386]:
v

array([[-1.87382499e-01, -1.60042346e-01,  9.29841954e-02,
        -1.05038456e-02, -1.86201406e-01, -2.00636068e-01,
        -1.23543539e-01, -5.19091667e-16, -1.47901556e-01,
        -2.74596107e-01, -6.92221656e-02,  2.84411887e-01,
        -2.16313817e-16,  1.56560945e-17, -2.40293747e-01,
         9.13602938e-02,  2.03508313e-01, -2.05251851e-01,
        -1.24581721e-01,  2.12917781e-01,  2.66347017e-01,
         1.95409709e-01, -2.05196772e-01,  2.95614861e-01,
         4.46064426e-01,  9.63845389e-02],
       [-4.08872413e-01, -2.80767526e-01,  1.96747493e-01,
         2.57747216e-01,  3.04862649e-01,  1.40876851e-01,
        -3.69317596e-01, -2.93428102e-16,  6.27176490e-02,
         1.91360933e-01,  1.03488636e-01,  3.00660476e-01,
        -1.24578694e-16, -7.91145519e-17, -2.24832282e-01,
        -2.54713638e-02,  1.96099444e-01, -3.87230790e-02,
         7.78066834e-02, -1.85345167e-01, -2.20244652e-01,
        -1.06901983e-01, -2.19026277e-02, -1.68533527e-01,
        -1.21

Taking largest 2 values

In [387]:
new_s=s[4:]
new_s

array([1.19546736, 1.43983171])

In [388]:
new_v=v[4:,:]
new_v

array([[ 2.46563957e-01,  9.76352632e-02, -5.15136379e-02,
        -2.65084467e-01, -2.33180103e-01, -2.32418966e-01,
         5.07826904e-02, -3.88610309e-17, -1.09095875e-01,
        -7.21794296e-02,  6.75370109e-02,  3.85749903e-01,
        -3.33189968e-17, -2.68849630e-16,  2.80331346e-02,
         3.28735405e-01,  8.70834883e-02, -2.55365659e-02,
        -1.77240390e-01, -3.31822223e-01, -3.51070536e-01,
        -3.84301712e-02, -1.13398367e-01, -7.02067537e-02,
        -2.12415504e-01,  3.59248058e-01],
       [ 2.45969259e-01,  3.89504749e-02,  4.20417013e-02,
         1.55821214e-01,  1.34106060e-01,  2.29663853e-01,
         1.70693635e-01,  3.44944770e-17,  7.57690698e-02,
         1.53749145e-01,  3.22977569e-01,  1.91275207e-01,
         1.53457342e-17,  2.00401709e-16,  2.35690757e-01,
         2.70831902e-01,  2.80453393e-01,  1.53680983e-01,
         3.16735856e-01,  2.42175500e-01,  2.36393578e-01,
         1.05243646e-01,  1.68421917e-01,  1.10942204e-01,
         9.09

In [389]:
new_u=u[:,4:]
new_u

array([[ 5.25382987e-02,  4.35164275e-02],
       [-4.05207165e-02,  4.99683387e-02],
       [-3.17667971e-02,  1.83182104e-02],
       [-9.65035467e-02,  7.91754142e-02],
       [-1.22530498e-02,  2.78608108e-02],
       [ 1.17847341e-01,  9.92664104e-02],
       [-1.64873664e-01,  1.08933710e-01],
       [-7.06817862e-02,  3.37512931e-02],
       [ 5.25382987e-02,  4.35164275e-02],
       [ 2.46557824e-02,  6.59279630e-02],
       [ 7.73217313e-02,  4.87864778e-02],
       [-1.72383459e-02,  3.04874319e-02],
       [ 1.35637343e-01,  9.95063120e-02],
       [ 1.00300279e-01,  6.86090598e-02],
       [ 8.02541867e-02,  6.83387344e-02],
       [ 5.25382987e-02,  4.35164275e-02],
       [-1.72383459e-02,  3.04874319e-02],
       [-5.96282219e-02,  2.11879566e-02],
       [ 3.45892073e-02,  1.14570459e-02],
       [-1.11996954e-01,  9.04205301e-02],
       [ 7.73217313e-02,  4.87864778e-02],
       [-1.72383459e-02,  3.04874319e-02],
       [-1.60913903e-17,  6.15340232e-18],
       [-9.

In [390]:
new_u.shape,new_s.shape,new_v.shape

((140, 2), (2,), (2, 26))

In [391]:
import numpy as np
r=new_u*new_s
result=np.dot(r,new_v)
result.shape

(140, 26)

In [393]:
from scipy.spatial import distance
df=pd.DataFrame(['vector1','vector2','similarity'])
for i in range(result.shape[0]):
    for j in range(result.shape[0]):
        cosine_similarity = 1 - distance.cosine(result[i], result[j])
        df.append({'vector1':i,'vector2':j,'similarity':cosine_similarity},ignore_index=True)

In [394]:
df

0
0     vector1
1     vector2
2  similarity

#### LSA method using building function

In [331]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
document=open('half girl friend.txt','r')
data=document.read()
data=data.split('\n')
vect=CountVectorizer()
bag_of_words=vect.fit_transform(data)
from sklearn.decomposition import TruncatedSVD
svd=TruncatedSVD(n_components=2)
lsa=svd.fit_transform(bag_of_words)
dictionary=vect.get_feature_names()
df=pd.DataFrame(lsa)
df['lines']=data
df

0             1  \
0   2.835278e+00 -1.673247e-01   
1   2.178668e+00  1.568487e+00   
2   6.655602e-01  4.755650e-01   
3   4.381270e-21 -5.406446e-20   
4   3.369781e+00 -2.116173e+00   
5   2.106489e+00  1.835469e+00   
6   1.780451e+00  4.969115e-01   
7  -3.178704e-20  1.190112e-18   
8   1.830019e+00 -1.300561e+00   
9   3.483725e+00 -3.344142e-02   
10  2.406446e+00  2.158871e+00   
11  4.224564e+00  4.741443e+00   
12  0.000000e+00 -0.000000e+00   
13  3.284679e+00 -1.205192e+00   
14  3.718456e+00 -1.530476e+00   
15  4.062897e+00  2.063214e+00   
16  4.624362e-13 -9.326543e-11   
17  0.000000e+00 -0.000000e+00   
18  3.576979e+00 -1.860629e+00   
19  1.720499e+00 -1.138482e+00   
20  0.000000e+00 -0.000000e+00   
21  4.157058e+00 -3.272134e+00   
22  4.215303e-01 -2.962954e-01   

                                                lines  
0   Madhav Jha, a rural boy from Dumraon, a villag...  
1   half-girlfriend, who he believes has died. Che...  
2   as his English wasn't good enough. Being a goo...  
3                                                      
4   The rich and beautiful Riya Somani is a girl f...  
5   association with basketball. Madhav wants to m...  
6   Riya parts company with him and tells him not ...  
7                                                      
8   A year later, Riya marries her childhood frien...  
9   Madhav decides to settle in his hometown Dumra...  
10   toilets – Madhav decides to meet local MLA ...  
11  visit to some schools in Bihar. Madhav tries h...  
12                                                     
13  In the course of his struggle, he comes across...  
14  after the speech, Riya leaves a letter for him...  
15  confesses her love for Madhav but states she h...  
16                                       disappeared.  
17                                                     
18  After three years, it is revealed from Riya's ...  
19  months of extensively searching, he finds her ...  
20                                                     
21  The book ends with the author visiting the rur...  
22                     school, and have a son, Shyam.

In [332]:
encoding_matrix=pd.DataFrame(svd.components_,index=['topic_1','topic_2'],columns=dictionary).T
encoding_matrix

topic_1   topic_2
about     0.016522  0.034133
across    0.022551 -0.019051
actually  0.019466 -0.002665
after     0.074647 -0.083034
alive     0.024559 -0.029416
...            ...       ...
who       0.104030 -0.030872
with      0.055228 -0.014907
year      0.012564 -0.020560
years     0.053100 -0.081143
york      0.024559 -0.029416

[212 rows x 2 columns]